# Libraries
library(boot)
library(foreach)
library(gdata)
library(geosphere)
library(ggpubr)
library(ggbeeswarm)
library(MASS)
library(PolisAPI)
library(sf)
library(survival)
library(tidyverse)
library(viridisLite)
